### ISSUE TITLE
Umbrella issue for ML team

### ISSUE THREAD

**Issue by EgorBu** [bblfsh/bblfshd#231]
Hello,
As we discussed in slack here it's umbrella issue for ML team. I will try to aggregate our wishes and problems here.

## Issues

Let's start with issues:

### bblfshd issues

- [ ] https://github.com/bblfsh/bblfshd/issues/159 *A lot of `<defunct>`*
- [ ] https://github.com/bblfsh/bblfshd/issues/164 *Cannot run on Windows*
- [ ] https://github.com/bblfsh/bblfshd/issues/168 *A lot of files in `/var/lib/bblfshd/tmp/`*
- [ ] https://github.com/bblfsh/bblfshd/issues/184 *Downgrading drivers doesn't yield functional drivers.*
- [x] https://github.com/bblfsh/bblfshd/issues/219 *Memory is not released, number of instances in `bblfshctl driver list` mismatch with `htop`*
- [X] https://github.com/bblfsh/bblfshd/issues/230 *Cannot install Go driver*
- [ ] (FR) https://github.com/bblfsh/bblfshd/issues/222 *Add Babelfishfile*
- [ ] (FR) https://github.com/bblfsh/bblfshd/issues/197 *Add a way to reinstall the driver with one command*

### Go & Python client issues

- [x] https://github.com/bblfsh/client-go/issues/100 *Question: how to get the node's token and internal type*
- [ ] https://github.com/bblfsh/client-python/issues/101 *[performance] queries are slow*
- [ ] https://github.com/bblfsh/client-python/issues/89 *ERROR:root:Exception deserializing message!*
- [X] https://github.com/bblfsh/client-python/issues/125 *Function `supported_languages` raises unimplemented exception*
- [X] https://github.com/bblfsh/client-python/issues/126 *`language` argument in `client.parse` changes number of files significantly*
- [ ] (FR) https://github.com/bblfsh/client-python/issues/108 *Add position information*

### Drivers

- [ ] (FR) https://github.com/bblfsh/go-driver/issues/13 *Comments are not merged*
- [X] https://github.com/bblfsh/javascript-driver/issues/22 *[bug] Missed token for regular expressions*
- [x] https://github.com/bblfsh/javascript-driver/issues/24 *[bug] roles: UNANNOTATED* 
- [X] https://github.com/bblfsh/javascript-driver/issues/25 *Multibyte characters break positions*
- [X] https://github.com/bblfsh/javascript-driver/issues/32 *\n should not be parsed in strings*
- [ ] https://github.com/bblfsh/python-driver/issues/142 *On EndPosition-s again*
- [x] https://github.com/bblfsh/python-driver/issues/143 *Errors while extracting all commits in pallets/jinja*
- [x] https://github.com/bblfsh/python-driver/issues/156 *Errors during installation of drivers*
- [X] (FR) ~~https://github.com/bblfsh/python-driver/issues/150 *Support Cython*~~
- [x] https://github.com/bblfsh/ocaml-driver/issues/8 *Error, malformed driver, missing manifest.toml*
- [x] https://github.com/bblfsh/rust-driver/issues/8 *Error, malformed driver, missing manifest.toml*

### SDK

- [ ] (FR) https://github.com/bblfsh/sdk/issues/252 *Add parent field into UAST Node in clients.*
- [ ] (FR) https://github.com/bblfsh/sdk/issues/291 *Include the information about full tokens*

### Web

- [x] (FR) https://github.com/bblfsh/web/issues/158 *Add installed drivers versions info*
- [ ] (FR) https://github.com/bblfsh/web/issues/42 *Add tree-like visualization*

### Miscellaneous

- [ ] https://github.com/bblfsh/documentation/issues/199 *`Babelfish (aka. bblfsh)` link is broken*
- [ ] (FR) https://github.com/bblfsh/libuast/issues/78 *Feature request: node hashes*

I believe that some of these issues can be closed already.

## Wishlist

Let's start second part about wishes (probably it's a bit late for new year's resolution but anyway).
It should show our priorities.

### Feature extraction for source code

This part is very important for everybody in MLonCode area and still it's quite complicated to do.
In summary:

* tokenization: `code` -> `nodes` -> `"".join(nodes) == code`
* parent information https://github.com/bblfsh/sdk/issues/252 - we use this info, these people use this info too https://github.com/tech-srl/ - this feature may increase usage of `bblfsh` by researchers in this area
* reserved keywords
* roles that are used in particular language

What we need (and not only we) - `code` -> `UAST` -> `code`. It's not possible right now so we did several tricks to overcome this problem.

We wrote [tokenizer](https://github.com/src-d/style-analyzer/tree/master/lookout/style/format/langs) for source code (right now only JS-lang is supported) that allows to do `code` -> {`UAST`, `info about parent of nodes`, `tokens`} where `tokens` has property `"".join(tokens) == code`.

To do it we had to find reserved keywords for particular language and made logic to split everything between UAST nodes with tokens into reserved keywords and spaces/quotes/newlines.

Also it's important to know which roles are used in particular language (obviously only subset of all roles is used for some language -> and it can be used to reduce dimensionality of features like we did [here](https://github.com/src-d/style-analyzer/blob/master/lookout/style/format/langs/javascript/roles.py))

### Position information

We rely heavily on position information of identifiers and literals - if it's not available - it makes our life much harder.

So we have to make workarounds like [this](https://github.com/src-d/style-analyzer/blob/master/lookout/style/format/langs/javascript/uast_fixers.py) for [[bug] Missed token for regular expressions](https://github.com/bblfsh/javascript-driver/issues/22).

How it can be checked - make long tests for each driver for 10-20-30 best repositories for each language and check that `node.token == code[node.start_offset:node.end_offset]`

### Integration/regression tests on popular repositories

Maybe proces the top 10-20-30 repositories for each supported language.

Make long running tests to check if everything is good with drivers-sdk-etc - it will allow to avoid many problems like 

- [ ] https://github.com/bblfsh/bblfshd/issues/159 *A lot of \<defunct\>*
- [x] https://github.com/bblfsh/bblfshd/issues/219 *Memory is not released, number of instances in `bblfshctl driver list` mismatch with `htop`* (probably related to #159).
- [X] https://github.com/bblfsh/javascript-driver/issues/22 *[bug] Missed token for regular expressions*
- [x] https://github.com/bblfsh/javascript-driver/issues/24 *[bug] roles: UNANNOTATED* 
- [X] https://github.com/bblfsh/javascript-driver/issues/25 *Multibyte characters break positions*

and so on.

### Language extensions

Follow up of this discussion https://src-d.slack.com/archives/C7UDG9VNY/p1533802242000193. In summary: https://github.com/babel/babel/ is excluded from our list of repos to check because more an issue of the native driver not covering all node types in this repo. Probably it's driver/`enry` issue to detect such kind of language extensions. (another example https://github.com/samgozman/YoptaScript#%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D1%8B)

### Partial parsing

It could help to check that code wasn't changed in the way to break parsing of UAST. Right now it just parse full content of file even if one space is added.

**Comment by zurk** [comment]
\+ https://github.com/bblfsh/bblfshd/issues/236 (JS driver related)

**Comment by dennwc** [comment]
**2)** was fixed in https://github.com/bblfsh/javascript-driver/pull/50

**Comment by dennwc** [comment]
I've checked the issues list and some of them are already resolved.

@creachadair Maybe we can make a separate project for this to track the progress?

**Comment by bzz** [comment]
Short-term and as a first step we could convert PR description to have a checkboxes and mark issues that are solved. Happy to do that, if nobody has any objections or better short-term suggestions.

**Comment by creachadair** [comment]
> Short-term and as a first step we could convert PR description to have a checkboxes and mark issues that are solved. Happy to do that, if nobody has any objections or better short-term suggestions.

It's a good idea, and I started working on this. So far I have mostly just rearranged things cosmetically, checking off items that are complete and separating out the FRs from the bugs.

**Comment by dennwc** [comment]
I think we can close this one, assuming all feature requests have their own issue filed.

**Comment by creachadair** [comment]
> I think we can close this one, assuming all feature requests have their own issue filed.

It looks that way. If I'm wrong, let me know and I'll take care of it.
