### ISSUE TITLE
Update Babelfish repository maintainers and add code owners

### ISSUE THREAD

**Issue by creachadair** [bblfsh/bblfshd#307]
Since the Language Analysis team has grown, the time has come to redistribute maintainership of the various repositories we maintain. Per the discussion during the [Q&A session](https://github.com/src-d/minutes/pull/718), [this sheet](https://docs.google.com/spreadsheets/d/1tHjtvFnsigFourjm9dEvJ6gdSsNc_9d7wBN3kgqvD3o/preview) contains the proposed reassignment.

Documentation for [CODEOWNERS file format](https://help.github.com/en/articles/about-code-owners). As much as possible I have tried to use the existing maintainers groups for auto-assignments.

☔️Repositories to reassign by category:

## Other

- [x] https://github.com/bblfsh/artwork (bblfsh/artwork#4)
- [x] https://github.com/bblfsh/documentation (bblfsh/documentation#279)
- [x] https://github.com/bblfsh/performance (bblfsh/performance#23)
- [x] ~https://github.com/bblfsh/sonar-checks~
- [x] ~https://github.com/bblfsh/web~
- [x] ~https://github.com/bblfsh/uast-viewer~

## Core

- [x] https://github.com/bblfsh/bblfshd (#308)
- [x] https://github.com/bblfsh/libuast (bblfsh/libuast#113)
- [x] https://github.com/bblfsh/sdk (bblfsh/sdk#435)
- [x] https://github.com/src-d/enry (src-d/enry#242)

## Clients

- [x] https://github.com/bblfsh/go-client (bblfsh/go-client#128)
- [x] https://github.com/bblfsh/tools (bblfsh/tools#23)
- [x] https://github.com/bblfsh/python-client (bblfsh/python-client#192)
- [x] https://github.com/bblfsh/scala-client (bblfsh/scala-client#132)

## Drivers

- [x] https://github.com/bblfsh/bash-driver (bblfsh/bash-driver#69)
- [x] https://github.com/bblfsh/clojure-driver (bblfsh/clojure-driver#8)
- [x] https://github.com/bblfsh/cpp-driver (bblfsh/cpp-driver#65)
- [x] https://github.com/bblfsh/csharp-driver (bblfsh/csharp-driver#47)
- [x] https://github.com/bblfsh/elixir-driver (bblfsh/elixir-driver#4)
- [x] https://github.com/bblfsh/erlang-driver (bblfsh/erlang-driver#12)
- [x] https://github.com/bblfsh/go-driver (bblfsh/go-driver#57)
- [x] https://github.com/bblfsh/java-driver (bblfsh/java-driver#131)
- [x] https://github.com/bblfsh/javascript-driver (bblfsh/javascript-driver#98)
- [x] https://github.com/bblfsh/lua-driver (bblfsh/lua-driver#6)
- [x] https://github.com/bblfsh/ocaml-driver (bblfsh/ocaml-driver#10)
- [x] https://github.com/bblfsh/php-driver (bblfsh/php-driver#57)
- [x] https://github.com/bblfsh/python-driver (bblfsh/python-driver#214)
- [x] https://github.com/bblfsh/python-pydetector (bblfsh/python-pydetector#27)
- [x] https://github.com/bblfsh/r-driver (bblfsh/r-driver#3)
- [x] https://github.com/bblfsh/ruby-driver (bblfsh/ruby-driver#54)
- [x] https://github.com/bblfsh/rust-driver (bblfsh/rust-driver#10)
- [x] https://github.com/bblfsh/typescript-driver (bblfsh/typescript-driver#25)

**Comment by creachadair** [comment]
All done! Congratulations to all the new owners. 😁
